version: "3.8"
services:
  database:
    build:
      context: ./database
    ports:
    - "1433:1433"
    container_name: database
  webserver:
    build:
      context: ./webserver
    environment:
      ASPNETCORE_CONNECTION_STRING: "Server=database,1433;Initial Catalog=WebAppDB;User ID=sa;Password=Start.1245;" # connectionString to database
    ports:
    - "5001:5001"
    container_name: webserver
  webapp:
    build:
      context: ./webapp
    environment:
      VUE_APP_SERVER_PORT: "5001" # port of the webserver
      VUE_APP_SERVER_NAME: "localhost" # ip of the server
    ports:
    - "80:8080"
    container_name: webapp
